sudo: false

language: haskell

git:
  depth: 5
  
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/NatalyaSlepkova/haskell-course-assistant/.stack-work"

matrix:
  include:

  - ghc: 8.2.2
    env: GHCVER='8.2.2' STACK_YAML="$HOME/build/NatalyaSlepkova/haskell-course-assistant/stack.yaml"
    
addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc'
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --haddock --no-haddock-deps
